-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 21:36:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Destinacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Destinacija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Destinacija` (
  `idDestinacija` INT NOT NULL,
  `drazava` VARCHAR(45) NOT NULL,
  `kraj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDestinacija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Potovanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Potovanje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Potovanje` (
  `idPotovanje` INT NOT NULL,
  `opis` TINYTEXT NOT NULL,
  PRIMARY KEY (`idPotovanje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vodja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vodja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vodja` (
  `maticnaSt` INT NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `izobrazba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`maticnaSt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TerminPotovanja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TerminPotovanja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TerminPotovanja` (
  `datum-od` INT NOT NULL,
  `datum-do` INT NOT NULL,
  `Potovanje_idPotovanje` INT NOT NULL,
  `Vodja_maticnaSt` INT NOT NULL,
  `cena` FLOAT NOT NULL,
  PRIMARY KEY (`datum-od`, `datum-do`, `Potovanje_idPotovanje`, `Vodja_maticnaSt`),
  INDEX `fk_TerminPotovanja_Potovanje1_idx` (`Potovanje_idPotovanje` ASC) VISIBLE,
  INDEX `fk_TerminPotovanja_Vodja1_idx` (`Vodja_maticnaSt` ASC) VISIBLE,
  CONSTRAINT `fk_TerminPotovanja_Potovanje1`
    FOREIGN KEY (`Potovanje_idPotovanje`)
    REFERENCES `mydb`.`Potovanje` (`idPotovanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TerminPotovanja_Vodja1`
    FOREIGN KEY (`Vodja_maticnaSt`)
    REFERENCES `mydb`.`Vodja` (`maticnaSt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Potovanje_has_Destinacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Potovanje_has_Destinacija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Potovanje_has_Destinacija` (
  `Potovanje_idPotovanje` INT NOT NULL,
  `Destinacija_idDestinacija` INT NOT NULL,
  PRIMARY KEY (`Potovanje_idPotovanje`, `Destinacija_idDestinacija`),
  INDEX `fk_Potovanje_has_Destinacija_Destinacija1_idx` (`Destinacija_idDestinacija` ASC) VISIBLE,
  INDEX `fk_Potovanje_has_Destinacija_Potovanje1_idx` (`Potovanje_idPotovanje` ASC) VISIBLE,
  CONSTRAINT `fk_Potovanje_has_Destinacija_Potovanje1`
    FOREIGN KEY (`Potovanje_idPotovanje`)
    REFERENCES `mydb`.`Potovanje` (`idPotovanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Potovanje_has_Destinacija_Destinacija1`
    FOREIGN KEY (`Destinacija_idDestinacija`)
    REFERENCES `mydb`.`Destinacija` (`idDestinacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NacinPrevoza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NacinPrevoza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NacinPrevoza` (
  `idNacinPrevoza` INT NOT NULL,
  `nacin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNacinPrevoza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TerminPotovanja_has_NacinPrevoza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TerminPotovanja_has_NacinPrevoza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TerminPotovanja_has_NacinPrevoza` (
  `TerminPotovanja_datum-od` INT NOT NULL,
  `TerminPotovanja_datum-do` INT NOT NULL,
  `TerminPotovanja_Potovanje_idPotovanje` INT NOT NULL,
  `TerminPotovanja_Vodja_maticnaSt` INT NOT NULL,
  `NacinPrevoza_idNacinPrevoza` INT NOT NULL,
  `datumUra` DATETIME NOT NULL,
  `krajOdhoda` VARCHAR(45) NOT NULL,
  `krajPrihoda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TerminPotovanja_datum-od`, `TerminPotovanja_datum-do`, `TerminPotovanja_Potovanje_idPotovanje`, `TerminPotovanja_Vodja_maticnaSt`, `NacinPrevoza_idNacinPrevoza`),
  INDEX `fk_TerminPotovanja_has_NacinPrevoza_NacinPrevoza1_idx` (`NacinPrevoza_idNacinPrevoza` ASC) VISIBLE,
  INDEX `fk_TerminPotovanja_has_NacinPrevoza_TerminPotovanja1_idx` (`TerminPotovanja_datum-od` ASC, `TerminPotovanja_datum-do` ASC, `TerminPotovanja_Potovanje_idPotovanje` ASC, `TerminPotovanja_Vodja_maticnaSt` ASC) VISIBLE,
  CONSTRAINT `fk_TerminPotovanja_has_NacinPrevoza_TerminPotovanja1`
    FOREIGN KEY (`TerminPotovanja_datum-od` , `TerminPotovanja_datum-do` , `TerminPotovanja_Potovanje_idPotovanje` , `TerminPotovanja_Vodja_maticnaSt`)
    REFERENCES `mydb`.`TerminPotovanja` (`datum-od` , `datum-do` , `Potovanje_idPotovanje` , `Vodja_maticnaSt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TerminPotovanja_has_NacinPrevoza_NacinPrevoza1`
    FOREIGN KEY (`NacinPrevoza_idNacinPrevoza`)
    REFERENCES `mydb`.`NacinPrevoza` (`idNacinPrevoza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
