-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 13:25:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SpletnaStran`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SpletnaStran` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SpletnaStran` (
  `idSpletnaStran` INT NOT NULL,
  `URLNaslov` VARCHAR(45) NOT NULL,
  `opisStrani` MEDIUMTEXT NULL,
  `administrator` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpletnaStran`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jed` (
  `idJed` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `energijskaVr` TINYINT NOT NULL,
  PRIMARY KEY (`idJed`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zvrst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Zvrst` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Zvrst` (
  `idZvrst` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZvrst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpletnaStran_has_Jed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SpletnaStran_has_Jed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SpletnaStran_has_Jed` (
  `SpletnaStran_idSpletnaStran` INT NOT NULL,
  `Jed_idJed` INT NOT NULL,
  `Zvrst_idZvrst` INT NOT NULL,
  PRIMARY KEY (`SpletnaStran_idSpletnaStran`, `Jed_idJed`),
  INDEX `fk_SpletnaStran_has_Jed_Jed1_idx` (`Jed_idJed` ASC) VISIBLE,
  INDEX `fk_SpletnaStran_has_Jed_SpletnaStran_idx` (`SpletnaStran_idSpletnaStran` ASC) VISIBLE,
  INDEX `fk_SpletnaStran_has_Jed_Zvrst1_idx` (`Zvrst_idZvrst` ASC) VISIBLE,
  CONSTRAINT `fk_SpletnaStran_has_Jed_SpletnaStran`
    FOREIGN KEY (`SpletnaStran_idSpletnaStran`)
    REFERENCES `mydb`.`SpletnaStran` (`idSpletnaStran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SpletnaStran_has_Jed_Jed1`
    FOREIGN KEY (`Jed_idJed`)
    REFERENCES `mydb`.`Jed` (`idJed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SpletnaStran_has_Jed_Zvrst1`
    FOREIGN KEY (`Zvrst_idZvrst`)
    REFERENCES `mydb`.`Zvrst` (`idZvrst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uporabnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Uporabnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Uporabnik` (
  `idUporabnik` INT NOT NULL,
  `uporabniskoIme` VARCHAR(45) NOT NULL,
  `geslo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUporabnik`),
  UNIQUE INDEX `uporabniskoIme_UNIQUE` (`uporabniskoIme` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recept` (
  `idRecept` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opisPostopka` MEDIUMTEXT NOT NULL,
  `Jed_idJed` INT NOT NULL,
  `Uporabnik_idUporabnik` INT NOT NULL,
  PRIMARY KEY (`idRecept`, `Uporabnik_idUporabnik`),
  INDEX `fk_Recept_Jed1_idx` (`Jed_idJed` ASC) VISIBLE,
  INDEX `fk_Recept_Uporabnik1_idx` (`Uporabnik_idUporabnik` ASC) VISIBLE,
  CONSTRAINT `fk_Recept_Jed1`
    FOREIGN KEY (`Jed_idJed`)
    REFERENCES `mydb`.`Jed` (`idJed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recept_Uporabnik1`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `mydb`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sestavina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sestavina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sestavina` (
  `idSestavina` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSestavina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recept_has_Sestavina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recept_has_Sestavina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recept_has_Sestavina` (
  `Recept_idRecept` INT NOT NULL,
  `Sestavina_idSestavina` INT NOT NULL,
  `kolicina` TINYINT NOT NULL,
  `enota` VARCHAR(10) NULL,
  PRIMARY KEY (`Recept_idRecept`, `Sestavina_idSestavina`),
  INDEX `fk_Recept_has_Sestavina_Sestavina1_idx` (`Sestavina_idSestavina` ASC) VISIBLE,
  INDEX `fk_Recept_has_Sestavina_Recept1_idx` (`Recept_idRecept` ASC) VISIBLE,
  CONSTRAINT `fk_Recept_has_Sestavina_Recept1`
    FOREIGN KEY (`Recept_idRecept`)
    REFERENCES `mydb`.`Recept` (`idRecept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recept_has_Sestavina_Sestavina1`
    FOREIGN KEY (`Sestavina_idSestavina`)
    REFERENCES `mydb`.`Sestavina` (`idSestavina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocena_recepta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ocena_recepta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ocena_recepta` (
  `Recept_idRecept` INT NOT NULL,
  `Recept_Uporabnik_idUporabnik` INT NOT NULL,
  `Uporabnik_idUporabnik` INT NOT NULL,
  `ocena` TINYINT NOT NULL,
  `komentar` TINYTEXT NULL,
  PRIMARY KEY (`Recept_idRecept`, `Recept_Uporabnik_idUporabnik`, `Uporabnik_idUporabnik`),
  INDEX `fk_Recept_has_Uporabnik_Uporabnik1_idx` (`Uporabnik_idUporabnik` ASC) VISIBLE,
  INDEX `fk_Recept_has_Uporabnik_Recept1_idx` (`Recept_idRecept` ASC, `Recept_Uporabnik_idUporabnik` ASC) VISIBLE,
  CONSTRAINT `fk_Recept_has_Uporabnik_Recept1`
    FOREIGN KEY (`Recept_idRecept` , `Recept_Uporabnik_idUporabnik`)
    REFERENCES `mydb`.`Recept` (`idRecept` , `Uporabnik_idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recept_has_Uporabnik_Uporabnik1`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `mydb`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
