-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 14:11:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Stranka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stranka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stranka` (
  `idStranka` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `naslov` VARCHAR(45) NOT NULL,
  `GSM` CHAR(9) NOT NULL,
  PRIMARY KEY (`idStranka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delavec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Delavec` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Delavec` (
  `idDelavec` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `davcnaSt` INT NOT NULL,
  `izobrazba` VARCHAR(45) NOT NULL,
  `naslov` VARCHAR(45) NOT NULL,
  `telefon` CHAR(9) NOT NULL,
  PRIMARY KEY (`idDelavec`, `ime`, `priimek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Popravilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Popravilo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Popravilo` (
  `idPopravilo` INT NOT NULL,
  `vrstaNaprave` VARCHAR(45) NOT NULL,
  `proizvajalec` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `serijskaSt` VARCHAR(45) NOT NULL,
  `opisProblema` MEDIUMTEXT NOT NULL,
  `datumPrejema` DATE NOT NULL,
  `stUrDela` TINYINT NOT NULL,
  `Stranka_idStranka` INT NOT NULL,
  `Delavec_idDelavec` INT NOT NULL,
  `Delavec_ime` VARCHAR(45) NOT NULL,
  `Delavec_priimek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPopravilo`, `Stranka_idStranka`, `Delavec_idDelavec`, `Delavec_ime`, `Delavec_priimek`),
  INDEX `fk_Popravilo_Stranka1_idx` (`Stranka_idStranka` ASC) VISIBLE,
  INDEX `fk_Popravilo_Delavec1_idx` (`Delavec_idDelavec` ASC, `Delavec_ime` ASC, `Delavec_priimek` ASC) VISIBLE,
  CONSTRAINT `fk_Popravilo_Stranka1`
    FOREIGN KEY (`Stranka_idStranka`)
    REFERENCES `mydb`.`Stranka` (`idStranka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Popravilo_Delavec1`
    FOREIGN KEY (`Delavec_idDelavec` , `Delavec_ime` , `Delavec_priimek`)
    REFERENCES `mydb`.`Delavec` (`idDelavec` , `ime` , `priimek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RezervniDel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RezervniDel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RezervniDel` (
  `idRezervniDel` INT NOT NULL,
  `opis` TINYTEXT NOT NULL,
  `cenaKos` FLOAT NOT NULL,
  PRIMARY KEY (`idRezervniDel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Popravilo_has_RezervniDel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Popravilo_has_RezervniDel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Popravilo_has_RezervniDel` (
  `Popravilo_idPopravilo` INT NOT NULL,
  `Popravilo_Stranka_idStranka` INT NOT NULL,
  `Popravilo_Delavec_idDelavec` INT NOT NULL,
  `Popravilo_Delavec_ime` VARCHAR(45) NOT NULL,
  `Popravilo_Delavec_priimek` VARCHAR(45) NOT NULL,
  `RezervniDel_idRezervniDel` INT NOT NULL,
  `kolicina` TINYINT NOT NULL,
  PRIMARY KEY (`Popravilo_idPopravilo`, `Popravilo_Stranka_idStranka`, `Popravilo_Delavec_idDelavec`, `Popravilo_Delavec_ime`, `Popravilo_Delavec_priimek`, `RezervniDel_idRezervniDel`),
  INDEX `fk_Popravilo_has_RezervniDel_RezervniDel1_idx` (`RezervniDel_idRezervniDel` ASC) VISIBLE,
  INDEX `fk_Popravilo_has_RezervniDel_Popravilo1_idx` (`Popravilo_idPopravilo` ASC, `Popravilo_Stranka_idStranka` ASC, `Popravilo_Delavec_idDelavec` ASC, `Popravilo_Delavec_ime` ASC, `Popravilo_Delavec_priimek` ASC) VISIBLE,
  CONSTRAINT `fk_Popravilo_has_RezervniDel_Popravilo1`
    FOREIGN KEY (`Popravilo_idPopravilo` , `Popravilo_Stranka_idStranka` , `Popravilo_Delavec_idDelavec` , `Popravilo_Delavec_ime` , `Popravilo_Delavec_priimek`)
    REFERENCES `mydb`.`Popravilo` (`idPopravilo` , `Stranka_idStranka` , `Delavec_idDelavec` , `Delavec_ime` , `Delavec_priimek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Popravilo_has_RezervniDel_RezervniDel1`
    FOREIGN KEY (`RezervniDel_idRezervniDel`)
    REFERENCES `mydb`.`RezervniDel` (`idRezervniDel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
