-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 21:59:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Komisija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Komisija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Komisija` (
  `idKomisija` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKomisija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izpit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Izpit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Izpit` (
  `idIzpit` INT NOT NULL,
  `datumIzvedbe` DATE NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `vrstaIzpita` VARCHAR(45) NOT NULL,
  `Komisija_idKomisija1` INT NOT NULL,
  PRIMARY KEY (`idIzpit`, `datumIzvedbe`),
  INDEX `fk_Izpit_Komisija1_idx` (`Komisija_idKomisija1` ASC) VISIBLE,
  CONSTRAINT `fk_Izpit_Komisija1`
    FOREIGN KEY (`Komisija_idKomisija1`)
    REFERENCES `mydb`.`Komisija` (`idKomisija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ucitelj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ucitelj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ucitelj` (
  `idUcitelj` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUcitelj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Komisija_has_Ucitelj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Komisija_has_Ucitelj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Komisija_has_Ucitelj` (
  `Komisija_idKomisija` INT NOT NULL,
  `Ucitelj_idUcitelj` INT NOT NULL,
  `leto` YEAR NOT NULL,
  `vloga` SET('predsednik', 'izprasevalec', 'clan') NOT NULL,
  PRIMARY KEY (`Komisija_idKomisija`, `Ucitelj_idUcitelj`, `leto`),
  INDEX `fk_Komisija_has_Ucitelj_Ucitelj1_idx` (`Ucitelj_idUcitelj` ASC) VISIBLE,
  INDEX `fk_Komisija_has_Ucitelj_Komisija_idx` (`Komisija_idKomisija` ASC) VISIBLE,
  CONSTRAINT `fk_Komisija_has_Ucitelj_Komisija`
    FOREIGN KEY (`Komisija_idKomisija`)
    REFERENCES `mydb`.`Komisija` (`idKomisija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Komisija_has_Ucitelj_Ucitelj1`
    FOREIGN KEY (`Ucitelj_idUcitelj`)
    REFERENCES `mydb`.`Ucitelj` (`idUcitelj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kandidat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kandidat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kandidat` (
  `emso` CHAR(13) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kandidat_has_Izpit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kandidat_has_Izpit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kandidat_has_Izpit` (
  `Kandidat_emso` CHAR(13) NOT NULL,
  `Izpit_idIzpit` INT NOT NULL,
  `Izpit_datumIzvedbe` DATE NOT NULL,
  `uraIzpita` TIME NOT NULL,
  `tocke` TINYINT NOT NULL,
  PRIMARY KEY (`Kandidat_emso`, `Izpit_idIzpit`, `Izpit_datumIzvedbe`),
  INDEX `fk_Kandidat_has_Izpit_Izpit1_idx` (`Izpit_idIzpit` ASC, `Izpit_datumIzvedbe` ASC) VISIBLE,
  INDEX `fk_Kandidat_has_Izpit_Kandidat1_idx` (`Kandidat_emso` ASC) VISIBLE,
  CONSTRAINT `fk_Kandidat_has_Izpit_Kandidat1`
    FOREIGN KEY (`Kandidat_emso`)
    REFERENCES `mydb`.`Kandidat` (`emso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kandidat_has_Izpit_Izpit1`
    FOREIGN KEY (`Izpit_idIzpit` , `Izpit_datumIzvedbe`)
    REFERENCES `mydb`.`Izpit` (`idIzpit` , `datumIzvedbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
